### ISSUE TITLE
power usage combined into 1st added insight

### ISSUE THREAD

**Issue by moekdegroot** [athombv/com.wemo#9] opened 2017-04-03 12:15 UTC
He @BasKiers ,

This weekend I installed some wemo insights and noticed that all power consumptions from all devices get send to the first added device.
When I open the device card of the first added device I see the power usage switching numbers corresponding to the power usage of the other two devices.
Off all three devices only the first one shows power usage, the other two show a - 
This happens if you install them one by one or if you install them all together at once.

Running homey firmware 1.2.0-rc.10
Wemo app: v2.1.9 - 11.12.16

All the best, Moek

**Comment by eppoedzes** [comment] 2017-05-12 08:41
Same here! And when I deleted the first Wemo and tried to repair it, Homey didn't find the Wemo Insight anymore.

**Comment by marcelwolf** [comment] 2017-05-15 20:11
I have the same problem. Also when i switch off the second one the first one is also switched. 
When is this going to be solved.

**Comment by BasKiers** [comment] 2017-10-31 14:46
Hi,

This issue should now be fixed as of v1.1.12 of the wemo app. However I could not reproduce the issue of @marcelwolf in which he mentions that the first device is also switched when switching a different device. If you are still experiencing this issue in the latest version of the wemo app please create a new issue.

Regards,
Bas

**Closed by BasKiers** 2017-10-31 14:46 UTC
Labels: bug
